name: Android (Vulkan)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: Kinc/make android -g vulkan --kinc Kinc --from Tests/Empty --noshaders --compile
