name: HTML5 (WebGPU)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile (kmake)
      run: Kinc/make html5 -g webgpu --kinc Kinc --from Tests/Empty --noshaders
    - name: Compile (emscripten)
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../build/Release && make
