name: macOS (OpenGL)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get krink Submodules
      run: git submodule update --init
    - name: Get Kinc DLC
      run: ./Kinc/get_dlc
    - name: Compile
      run: Kinc/make -g opengl --kinc Kinc --from Tests/Empty --noshaders --compile
