name: UWP

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: .\Kinc\make.bat windowsapp -v vs2022 --kinc Kinc --from Tests/Empty --noshaders --compile
