name: Windows (Direct3D 11)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get krink Submodules
      run: git submodule update --init
    - name: Get Kinc DLC
      run: .\Kinc\get_dlc.bat
    - name: Compile
      run: .\Kinc\make.bat -v vs2022 -g direct3d11 --kinc Kinc --from Tests/Empty --compile

    # TODO: make comparison test
    # - name: Get ImageMagick
    #   run: |
    #     choco install -y imagemagick.app --no-progress
    #     Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'ImageMagick*')} | % { $_.FullName } | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    # - name: Compile and run Test 1
    #   run: .\Kinc\make.bat -v vs2022 -g direct3d11 --kinc Kinc --from Tests/Shader --run
    # - name: Check Test 1
    #   run: magick compare -metric mae .\Tests\Shader\reference.png .\Tests\Shader\Deployment\test.png difference.png
