name: Windows (Direct3D 9)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: .\Kinc\make.bat -v vs2022 -g direct3d9 -a directsound --kinc Kinc --from Tests/Empty --noshaders --compile
